Error in rule kmer_dataframe:
    jobid: 0
    output: suis_kmer_counts.csv

RuleException:
CalledProcessError in line 67 of /home/ashlynn/Desktop/Fall_2019/Brucella/source/suis/suis_jellyfish.smk:
Command ' set -euo pipefail;  python suis_count_to_df.py ' returned non-zero exit status 1.
  File "/home/ashlynn/Desktop/Fall_2019/Brucella/source/suis/suis_jellyfish.smk", line 67, in __rule_kmer_dataframe
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
